#!/bin/sh
ISO=$1
MNTDIR=$2

VER=1.0
AUTHOR='Pontvieux Cyrille - jrd@enialis.net'
LICENCE='GPL v3+'
version() {
  echo "install-on-USB v$VER by $AUTHOR"
  echo "Licence : $LICENCE"
  echo '→ Install an ISO that use grub2 on an USB key'
}

usage() {
  version
  echo ''
  echo 'usage : install-on-USB.sh ISO_FILE USB_MOUNT_DIR'
  echo ''
  echo '  ISO_FILE : the full path to the ISO'
  echo '  USB_MOUNT_DIR : the full path to mounted dir of the USB key'
  echo '                  ex: /media/MyUSB'
  exit 1
}

if [ ! -f "$ISO" -o ! -d "$MNTDIR" ]; then
  usage
fi
DEVPART=$(mount | grep "on $MNTDIR" | cut -d' ' -f1 | head -n 1)
DEVROOT=${DEVPART%${DEVPART: -1}}
GAP=$(fdisk -l -u $DEVROOT | grep "^${DEVROOT}1" | awk '{print $3}')
if [ "$GAP" -lt 63 ]; then
  echo "Error : the post MBR gap is missing or not enough (63 sectors)."
  echo "Suggestion : move the first partition (${DEVROOT}1) to reach the gap."
  exit 2
fi
T=$(mktemp -d)
trap "umount $T; rm -rf $T" INT TERM EXIT
mount -o loop $ISO $T || exit 3
cp -rv $T/* $MNTDIR/ || exit 4
grub-install --root-directory=$MNTDIR $DEVROOT || exit 5
exit 0
